### ISSUE TITLE
Update leaderboard views

### ISSUE THREAD

**Issue by s-c-orr** [moonstream-to/fullcount.xyz#209]
Update leaderboards to show character names and images and players' usernames. It should be easy for players to identify their characters on the leaderboards.

- [x] Designed
- [ ] Reviewed
- [ ] Live

**Comment by ishihssihshihishsi** [comment]
@s-c-orr @Anton-Mushnin leaderboards are updated – [link to figma](https://www.figma.com/file/UFGpJDqaro5USYCXbmGvba/Fullcount?type=design&node-id=3335-11675&mode=design&t=akMthmXjf3P66dh8-4). similar layout can be implemented to the moonstream style leaderboard (original moonstream leaderboard frontend) but with space grotesk font, @Anton-Mushnin let me know if you need a design for it.
