### ISSUE TITLE
Game client should be able to display tokens whose metadata is not a data URI

### ISSUE THREAD

**Issue by zomglings** [moonstream-to/fullcount.xyz#64]
Most NFT collections host their metadata on a server and do not deliver it using a data URI.

The frontend currently only accepts Data URIs. It completely crashes if someone creates a session with an NFT from a collection that hosts its metadata on a server.

https://github.com/moonstream-to/fullcount.xyz/pull/63 is a quick fix, but the correct solution would correctly handle both cases with a graceful default if neither succeeded.

**Comment by Anton-Mushnin** [comment]
https://github.com/moonstream-to/fullcount.xyz/pull/66
